# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('phone_number', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=6)),
                ('id_number', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('nhif_number', models.IntegerField(default=0)),
                ('blood_group', models.CharField(max_length=5)),
            ],
        ),
    ]
