# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergiesAndDirectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_number', models.IntegerField()),
                ('specialty', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(upload_to='doctor_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_cover', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_given', models.DateTimeField()),
                ('doctor_prescribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faith_pms.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='nhif_number',
            new_name='NHIF_number',
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies_and_directives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faith_pms.AllergiesAndDirectives'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faith_pms.MedicalCover'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faith_pms.Medicine'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faith_pms.NextOfKin'),
        ),
    ]
