# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0004_doctor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.IntegerField(null=True),
        ),
    ]
