# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0005_auto_20180213_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
