# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0007_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='patients_photo/'),
        ),
    ]
