# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0008_patient_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
