# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0009_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.CharField(default='Medical Doctor', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(default='Nairobi Hospital', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.IntegerField(default=12345, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Treat Me', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(default='doctor_profiles/no-image.jpg', upload_to='doctor_profiles/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='Physician', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(default='Dr', max_length=20, null=True),
        ),
    ]
