# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0010_auto_20180214_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('diagnosis', models.CharField(max_length=1000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faith_pms.Doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faith_pms.Medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faith_pms.Patient')),
            ],
        ),
    ]
