# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0011_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='recommendations',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
