# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith_pms', '0012_treatment_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='cost',
            new_name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='medicine',
        ),
        migrations.AddField(
            model_name='treatment',
            name='symptoms',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
